### ISSUE TITLE
rtc examples do not work

### ISSUE THREAD

**Issue by edge-tech-eu** [arduino-libraries/Arduino_EdgeControl#12]
the rtc example (RTCClock in `examples/Application`) in this repository does not work. the code compiles and sets the data&time correctly but when commenting out the line that sets the time&date (`setSystemClock(__DATE__, __TIME__)`) the timer restarts. it does not remember the time&date set before. see below

the rtc excample (RealTimeClock in `examples/Basic`) in this repository does also not work as it fails to detect the rtc. see below.

also i noticed that the rtc (u22) is not on the schematics as on the website (https://docs.arduino.cc/hardware/edge-control) date 27/07/2020

thanks
frank

RealTimeClock:

```text
Hello, Arduino Edge Control!
Initializating the Real Time Clock... failed! Retrying...
 failed! Retrying...
 failed! Retrying...
 failed! Retrying...
 failed! Retrying...
 failed! Retrying...
```

RTCClock:

```text
Starting RTC example
Compile Date and Time: 2022-05-16 19:33:18
RTC Date and Time:     1970-01-01  0:00:00
System Clock:          2022-05-16 19:33:18
2022-05-16 19:33:18
2022-05-16 19:33:19
2022-05-16 19:33:20
2022-05-16 19:33:21
2022-05-16 19:33:22
2022-05-16 19:33:23
2022-05-16 19:33:24
2022-05-16 19:33:25
2022-05-16 19:33:26
2022-05-16 19:33:27
2022-05-16 19:33:28
2022-05-16 19:33:29
2022-05-16 19:33:30
2022-05-16 19:33:31
2022-05-16 19:33:32
2022-05-16 19:33:33
2022-05-16 19:33:34

Starting RTC example
1970-01-01  0:00:00
1970-01-01  0:00:00
1970-01-01  0:00:01
1970-01-01  0:00:02
1970-01-01  0:00:03
```

**Comment by manchoz** [comment]
Hi @edge-tech-eu,
the RTC component is only present in the latest revision of the board, which will be available in the store soon.

On all the revisions of the boards, when you don't need the RTC surviving resets, you can still use the nRF52840's [Real-Time Counter](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf52840%2Frtc.html) via the MbedOS [RTC](https://os.mbed.com/docs/mbed-os/v6.15/apis/time-apis.html) and [Time](https://os.mbed.com/docs/mbed-os/v6.15/apis/time.html) APIs as shown in [RTCClock.ino](https://github.com/arduino-libraries/Arduino_EdgeControl/blob/master/examples/Application/RTCClock/RTCClock.ino).
