### ISSUE TITLE
Edge control's solid state relay and RTC

### ISSUE THREAD

**Issue by brinata** [arduino-libraries/Arduino_EdgeControl#16]
Hello,

I'm testing the  SSR relay on Edge control board, but sometimes the device fails, it doesn't "catch" the command and it doesn't change its state. I'm using the Edge control software library and I'm driving the SSR device with 24V DC voltage ( reading the datasheet it seems "workable" also at zero frequency..)

Moreover, I need to understand if will be commercialized the version with the hardware RTC device, and, if yes, when.

Regards

**Comment by per1234** [comment]
Hi @brinata. Thanks for your report.

>I need to understand if will be commercialized the version with the hardware RTC device, and, if yes, when.

This issue tracker is only used for bug reports and feature requests related to the Arduino_EdgeControl library code. For questions about the [Arduino Edge Control](https://www.arduino.cc/pro/hardware/product/edge-control) product, please contact Arduino support via this form:

https://www.arduino.cc/pro/contact-us

**Comment by brinata** [comment]
hi @per1234,

I've wrote to the customer support to know about the new version of the board. 

Anyway, can anyone help me about the SSR bug:

'm testing the SSR relay on Edge control board, but sometimes the device fails, it doesn't "catch" the command and it doesn't change its state. I'm using the Edge control software library and I'm driving the SSR device with 24V DC voltage ( reading the datasheet it seems "workable" also at zero frequency..)

Regards

**Comment by per1234** [comment]
This isn't a place to get help with your project. Bug reports are always welcome, but these are submitted in order to contribute to the development of this free open source software.

If you want help, please post on the Arduino forum. There is a dedicated section for the Edge Control here:

https://forum.arduino.cc/c/hardware/portenta/edge-impulse/178

**Comment by brinata** [comment]
I was in touch with [manchoz] and he wrote me to post here about questions on Edge control: he was informed about this isse and he wrote me that he would have done some test about it.
