### ISSUE TITLE
Power.getVBat() not getting the correct battery voltage

### ISSUE THREAD

**Issue by Goliath86** [arduino-libraries/Arduino_EdgeControl#19]
I've connected an Edge Control board to only a 12V battery (no solar panel connected) and with the function Power.getVBat() I read a 10.25V when the real battery's voltage is 12.33V readed with a multimeter.

**Comment by manchoz** [comment]
Hi,
please try commenting out [line 75](https://github.com/arduino-libraries/Arduino_EdgeControl/blob/552e356c56621cd0c4e00a1dcf67c1f7164c0e9c/src/EdgeControl_Power.cpp#L75) from the library.

The implementation is straightforward: it is just converting the readings from samples to voltage and applying the voltage divider back. Something must be wrong in the middle.

**Comment by Goliath86** [comment]
It seems that a RS232/RS485 circuit that I apply to the MKR2 socket draw the battery at 10.3V. If I disconnect it I read the correct voltage even without commenting the line 75 on the library.

I don't know why this happen. I use this circuit to the MKR2 socket:

![Jopto](https://github.com/arduino-libraries/Arduino_EdgeControl/assets/16368922/bdfdfeb3-5f8b-4ee4-879b-00fd30378719)

Otherwise I think that we can close this "issue". Thanks again

**Comment by manchoz** [comment]
Hi,
How are you powering the adapter? Do you have any specifications for the component?

**Comment by Goliath86** [comment]
Unfortunately there are no specs but the circuit seems to use the MAX13487E transceiver that seems to work at 5VDC on input but the Edge board work at 3.3VDC. Indeed on the TXD pin of the transceiver there are 5VDC but the Edge board only accept voltage at 3.3VDC on that pin. If I put a 10Kohm on that pin as a workaround, then the Power.getVBat() works as expected and return 12.3V

**Comment by manchoz** [comment]
Good.

Also, you may want to try a 3.3v-compatible TTL UART to RS485 converter: they are pretty popular.

**Comment by Goliath86** [comment]
> Good.
> 
> Also, you may want to try a 3.3v-compatible TTL UART to RS485 converter: they are pretty popular.

Yes, 
I only had that type of converter at home but for the next time I will buy a compatible one. Thank you for the support!

**Comment by manchoz** [comment]
You welcome!
