### ISSUE TITLE
How can I use the QSPI with the external QSPI flash chip?

### ISSUE THREAD

**Issue by bigbearishappy** [arduino-libraries/Arduino_EdgeControl#7]
Hello.
I find that the mcu is connected to external flash with the QSPI interface.
But I can't find a demo code in this repo.
I can just find the demo which use the [external flash with spi flash](https://github.com/arduino-libraries/Arduino_EdgeControl/blob/master/examples/Storage/StoragePartitions/StoragePartitions.ino)

Can anyone help me?
Thank you~

**Comment by manchoz** [comment]
Hi @bigbearishappy,
the QSPI interface is not supported at this moment. You need to stay on SPI.

**Comment by bigbearishappy** [comment]
> Hi @bigbearishappy, the QSPI interface is not supported at this moment. You need to stay on SPI.

OK，I got it.
Thank you for your reply.
